/** REST API paths — mirrors diet-elite-api/resources/js/lib/api-routes.ts */
export const apiRoutes = {
    auth: {
        login: '/api/v1/auth/login',
        logout: '/api/v1/auth/logout',
        me: '/api/v1/auth/me',
    },
    dashboard: '/api/v1/dashboard',
    profile: {
        show: '/api/v1/profile',
        update: '/api/v1/profile',
        photo: '/api/v1/profile/photo',
    },
    notifications: {
        index: '/api/v1/notifications',
        readAll: '/api/v1/notifications/read-all',
        clearAll: '/api/v1/notifications/clear-all',
        read: (id: string) => `/api/v1/notifications/${id}/read`,
    },
    plans: {
        index: '/api/v1/plans',
        compare: '/api/v1/plans/compare',
        show: (planId: string) => `/api/v1/plans/${planId}`,
        checkout: (planId: string) => `/api/v1/plans/${planId}/checkout`,
    },
    payments: {
        index: '/api/v1/payments',
        confirm: (paymentId: string) => `/api/v1/payments/${paymentId}/confirm`,
    },
    bookings: {
        index: '/api/v1/bookings',
        store: '/api/v1/bookings',
        calendar: '/api/v1/bookings/calendar',
        cancel: (bookingId: string) => `/api/v1/bookings/${bookingId}/cancel`,
    },
    dietitians: {
        search: '/api/v1/dietitians/search',
    },
    reviews: {
        index: '/api/v1/reviews',
        store: '/api/v1/reviews',
    },
    healthProfile: {
        show: '/api/v1/health-profile',
        update: '/api/v1/health-profile',
    },
    mealPlan: '/api/v1/meal-plan',
    aiCoach: {
        index: '/api/v1/ai-coach',
        suggest: '/api/v1/ai-coach/suggest',
    },
    messages: {
        index: '/api/v1/messages',
        start: '/api/v1/messages/start',
        show: (threadId: string) => `/api/v1/messages/${threadId}`,
        store: (threadId: string) => `/api/v1/messages/${threadId}`,
    },
    dietitian: {
        dashboard: '/api/v1/dietitian/dashboard',
        appointments: '/api/v1/dietitian/appointments',
        appointmentShow: (id: string) => `/api/v1/dietitian/appointments/${id}`,
        appointmentApprove: (id: string) => `/api/v1/dietitian/appointments/${id}/approve`,
        appointmentReject: (id: string) => `/api/v1/dietitian/appointments/${id}/reject`,
        appointmentCancel: (id: string) => `/api/v1/dietitian/appointments/${id}/cancel`,
        appointmentComplete: (id: string) => `/api/v1/dietitian/appointments/${id}/complete`,
        clients: '/api/v1/dietitian/clients',
        clientShow: (userId: string) => `/api/v1/dietitian/clients/${userId}`,
        customersSearch: '/api/v1/dietitian/customers/search',
        messages: {
            index: '/api/v1/dietitian/messages',
            startDirect: '/api/v1/dietitian/messages/start',
            startClient: (userId: string) => `/api/v1/dietitian/clients/${userId}/messages`,
            show: (threadId: string) => `/api/v1/dietitian/messages/${threadId}`,
            store: (threadId: string) => `/api/v1/dietitian/messages/${threadId}`,
        },
    },
    advisor: {
        dashboard: '/api/v1/advisor/dashboard',
        enrollments: '/api/v1/advisor/enrollments',
        enrollmentsStore: '/api/v1/advisor/enrollments',
        bookings: '/api/v1/advisor/bookings',
        bookingsCreate: '/api/v1/advisor/bookings/create',
        bookingsStore: '/api/v1/advisor/bookings',
        customersSearch: '/api/v1/advisor/customers/search',
        messages: {
            index: '/api/v1/advisor/messages',
            start: '/api/v1/advisor/messages/start',
            show: (threadId: string) => `/api/v1/advisor/messages/${threadId}`,
            store: (threadId: string) => `/api/v1/advisor/messages/${threadId}`,
        },
    },
    admin: {
        dashboard: '/api/v1/admin/dashboard',
        auditLog: '/api/v1/admin/audit-log',
        plans: {
            index: '/api/v1/admin/plans',
            create: '/api/v1/admin/plans/create',
            store: '/api/v1/admin/plans',
            show: (id: string) => `/api/v1/admin/plans/${id}`,
            edit: (id: string) => `/api/v1/admin/plans/${id}/edit`,
            update: (id: string) => `/api/v1/admin/plans/${id}`,
            destroy: (id: string) => `/api/v1/admin/plans/${id}`,
        },
        categories: {
            index: '/api/v1/admin/categories',
            create: '/api/v1/admin/categories/create',
            store: '/api/v1/admin/categories',
            edit: (id: string) => `/api/v1/admin/categories/${id}/edit`,
            update: (id: string) => `/api/v1/admin/categories/${id}`,
            destroy: (id: string) => `/api/v1/admin/categories/${id}`,
        },
        planRanks: {
            index: '/api/v1/admin/plan-ranks',
            create: '/api/v1/admin/plan-ranks/create',
            store: '/api/v1/admin/plan-ranks',
            edit: (id: string) => `/api/v1/admin/plan-ranks/${id}/edit`,
            update: (id: string) => `/api/v1/admin/plan-ranks/${id}`,
            destroy: (id: string) => `/api/v1/admin/plan-ranks/${id}`,
        },
        bookings: {
            index: '/api/v1/admin/bookings',
            create: '/api/v1/admin/bookings/create',
            store: '/api/v1/admin/bookings',
            show: (id: string) => `/api/v1/admin/bookings/${id}`,
            approve: (id: string) => `/api/v1/admin/bookings/${id}/approve`,
            reject: (id: string) => `/api/v1/admin/bookings/${id}/reject`,
            cancel: (id: string) => `/api/v1/admin/bookings/${id}/cancel`,
            complete: (id: string) => `/api/v1/admin/bookings/${id}/complete`,
        },
        users: {
            index: '/api/v1/admin/users',
            create: '/api/v1/admin/users/create',
            store: '/api/v1/admin/users',
            show: (id: string) => `/api/v1/admin/users/${id}`,
            edit: (id: string) => `/api/v1/admin/users/${id}/edit`,
            update: (id: string) => `/api/v1/admin/users/${id}`,
            downgradePlan: (id: string) => `/api/v1/admin/users/${id}/downgrade-plan`,
        },
        payments: {
            index: '/api/v1/admin/payments',
        },
        customers: {
            search: '/api/v1/admin/customers/search',
        },
        messages: {
            index: '/api/v1/admin/messages',
            start: '/api/v1/admin/messages/start',
            show: (threadId: string) => `/api/v1/admin/messages/${threadId}`,
            store: (threadId: string) => `/api/v1/admin/messages/${threadId}`,
        },
        schedules: {
            index: '/api/v1/admin/schedules',
            show: (dietitianId: string) => `/api/v1/admin/schedules/${dietitianId}`,
            store: (dietitianId: string) => `/api/v1/admin/dietitians/${dietitianId}/schedules`,
            update: (dietitianId: string, scheduleId: string) =>
                `/api/v1/admin/dietitians/${dietitianId}/schedules/${scheduleId}`,
            destroy: (dietitianId: string, scheduleId: string) =>
                `/api/v1/admin/dietitians/${dietitianId}/schedules/${scheduleId}`,
        },
    },
} as const;
